import type { PatternRenderer } from '../../../types/grid';

export const drawIsometricGrid: PatternRenderer = (
  ctx,
  width,
  height,
  spacingPx,
  opacity,
  color,
) => {
  ctx.save();
  ctx.globalAlpha = opacity;
  ctx.fillStyle = color;

  // Triangular lattice basis vectors (60°)
  const ux = spacingPx;
  const uy = 0;
  const vx = spacingPx / 2;
  const vy = (spacingPx * Math.sqrt(3)) / 2;

  // Calculate how many points needed to cover the canvas
  // We'll iterate over i,j and draw points at p = i*u + j*v
  // Also include points at p + (u+v)/2? Actually triangular lattice has points at integer combinations,
  // but to get the full triangular tiling we need two sets: one at i*u+j*v and another at i*u+j*v + (u+v)/2?
  // Actually the standard triangular lattice (equilateral triangles) has points at all integer combinations of u and v.
  // That gives a honeycomb of triangles? Actually that gives a rhombic lattice, not triangular.
  // For a true triangular tiling (with triangles pointing up and down), we need to include both sets:
  // Set A: i*u + j*v
  // Set B: i*u + j*v + (u+v)/2   (the centers of the triangles, but we want the vertices, so we might want the other orientation)
  // Wait: The vertices of a triangular tiling are simply the integer lattice generated by u and v. That's correct.
  // Because each triangle has vertices at (i,j), (i+1,j), (i,j+1) in lattice coordinates.
  // So just integer combinations are enough.

  // Determine range of i and j such that points are within the canvas
  // We'll use a bounding box approach: for a given i,j, the point x = i*ux + j*vx, y = i*uy + j*vy.
  // We can solve for i,j ranges by projecting.

  // Simpler: loop over a grid of indices with enough margin.
  const margin = 2; // extra rows/cols beyond canvas
  const cols = Math.ceil(width / spacingPx) + margin;
  const rows = Math.ceil(height / vy) + margin; // approximate

  // Also we need to include the offset for the second set to make full triangles?
  // Actually the integer lattice already gives all vertices. To get the downward triangles, we need to add the center points?
  // No, the vertices are all at integer combinations. The centers are not vertices.
  // So we just draw dots at integer combinations.

  // However, to get a uniform appearance, we might want to also include points that are shifted by (u+v)/2? That would be the centers, but those are not vertices.
  // If we want a triangular pattern of dots, we can just draw dots at the integer lattice points. That gives a triangular arrangement.

  // Let's also include the points from the other orientation to make it look like a full triangular grid? The user said "triangle dots", so maybe they want dots at all intersections of isometric lines, which is the same as the lattice points.

  // We'll loop i from -margin to cols+margin, j from -margin to rows+margin
  for (let i = -margin; i < cols + margin; i++) {
    for (let j = -margin; j < rows + margin; j++) {
      const x = i * ux + j * vx;
      const y = i * uy + j * vy;
      // Check if point is within canvas bounds (plus a bit of padding)
      if (x >= -spacingPx && x <= width + spacingPx && y >= -spacingPx && y <= height + spacingPx) {
        ctx.beginPath();
        ctx.arc(x, y, spacingPx * 0.07, 0, Math.PI * 2); // dot size proportional to spacing
        ctx.fill();
      }
    }
  }

  ctx.restore();
};
